# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('lastSuccessfulBuild', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastUnsuccessfulBuild', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastAbortedBuild', models.DateTimeField(default=django.utils.timezone.now)),
                ('spec_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
