# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildJobInfo',
            fields=[
                ('build_id', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.CharField(blank=True, max_length=1000, null=True)),
                ('build_no', models.IntegerField(blank=True, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('build_id_jenkins', models.TextField(blank=True, null=True)),
                ('build_tags', models.TextField(blank=True, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('arch', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('zip_location', models.TextField(blank=True, null=True)),
                ('rpm_location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'build_job_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuildRequest',
            fields=[
                ('product_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('version', models.CharField(blank=True, max_length=1000, null=True)),
                ('release', models.CharField(blank=True, max_length=1000, null=True)),
                ('platform_os_id', models.IntegerField(blank=True, null=True)),
                ('platform_ws_id', models.IntegerField(blank=True, null=True)),
                ('product_arch_id', models.IntegerField(blank=True, null=True)),
                ('output_directory', models.CharField(blank=True, max_length=1000, null=True)),
                ('input_type_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('build_type_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('platform_spec_id', models.IntegerField(blank=True, null=True)),
                ('build_status', models.CharField(blank=True, max_length=1000, null=True)),
                ('request_time', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('file', models.CharField(blank=True, max_length=1000, null=True)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('release_notes_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('release_notes', models.CharField(max_length=1000)),
                ('derived_build_id', models.IntegerField(blank=True, null=True)),
                ('build_id', models.IntegerField(blank=True, null=True)),
                ('job_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'build_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuildType',
            fields=[
                ('build_type_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('build_type_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'build_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('input_type_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('input_type_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'input_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformArch',
            fields=[
                ('arch_id', models.AutoField(primary_key=True, serialize=False)),
                ('arch_name', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'platform_arch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformJre',
            fields=[
                ('jre_id', models.AutoField(primary_key=True, serialize=False)),
                ('jre_name', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'platform_jre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformOs',
            fields=[
                ('os_id', models.AutoField(primary_key=True, serialize=False)),
                ('os_name', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'platform_os',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformSpecIdvsproductName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_spec_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_spec_idvsproduct_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformSpecVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_platform_spec_id', models.IntegerField(blank=True, null=True)),
                ('version_a', models.CharField(blank=True, max_length=1000, null=True)),
                ('version_b', models.CharField(blank=True, max_length=1000, null=True)),
                ('version_c', models.CharField(blank=True, max_length=1000, null=True)),
                ('version_d', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('derived_build_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'platform_spec_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformWs',
            fields=[
                ('ws_id', models.AutoField(primary_key=True, serialize=False)),
                ('ws_name', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'platform_ws',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('filename', models.CharField(blank=True, max_length=1000, null=True)),
                ('branch', models.CharField(blank=True, max_length=10, null=True)),
                ('release', models.CharField(blank=True, max_length=1000, null=True)),
                ('fixes', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('impact_area', models.TextField(blank=True, null=True)),
                ('test_cases', models.TextField(blank=True, null=True)),
                ('synchronisation_status', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('platform_spec_id', models.IntegerField(blank=True, null=True)),
                ('build_version', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'release_notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RpmMakeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=1000, null=True)),
                ('module', models.CharField(blank=True, max_length=1000, null=True)),
                ('version', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('release', models.CharField(blank=True, max_length=1000, null=True)),
                ('base', models.CharField(blank=True, max_length=1000, null=True)),
                ('base_command', models.CharField(blank=True, max_length=1000, null=True)),
                ('revision_command', models.CharField(blank=True, max_length=1000, null=True)),
                ('file', models.CharField(blank=True, max_length=1000, null=True)),
                ('md5', models.CharField(blank=True, max_length=1000, null=True)),
                ('dir', models.CharField(blank=True, max_length=1000, null=True)),
                ('mode', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rpm_make_info',
                'managed': False,
            },
        ),
    ]
